language: go
go:
  - 1.8
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
install:
  - go get -u github.com/gopherjs/gopherjs
  - go get -tags levelupjs github.com/fiatjaf/summadb/...
script:
  - npm run test
